### ISSUE TITLE
Add Custom Post Type Support

### ISSUE THREAD

**Issue by mrjarbenne** [hwdsb/simple-wp-notify-pending#1]
What would be optimum would be a check list on the Admin page where the different post types that trigger a notification could be selected. 

Something similar to this https://github.com/hwdsb/subscribe-by-email/commit/3fc243c50dceeaa795cd93a38ec088b17f594df3

![2021-03-05_11-54-15](https://user-images.githubusercontent.com/480667/110147334-8c328c00-7da9-11eb-909c-5f485db483e2.png)

The request is coming from a need to get notified about pending 'slides' post type entries from our Presentation plugin, so without an admin option, we could add a check for ( get_post_type( $post_id ) === 'slides' ) instead if that's easier.

**Comment by r-a-y** [comment]
I decided to just use a simple code snippet to send an email to the site admin whenever there is a pending slide in our `reveal-stuff.php` plugin.

Here's what I'm using for the email contents:

**Subject** -  `New slide is pending review: {slide_title}`

**Message**

```
Hi,

{user_login} just created a new slide, "{slide_title}".

Edit the slide here: {slide_edit_url}
```

Let me know if you want to modify the copy. For our presentations plugin, I had to fix an issue with how the default post title wasn't being set during pending status. See https://github.com/hwdsb/reveal-presentations/commit/1c2677a687b14670fce8574adc0d7cafd9ad0e2e.

I also fixed a bug during editing where the presentation theme was not being applied: https://github.com/hwdsb/reveal-presentations/commit/5593d8311b842a035a3975f1a684d619e02ba00a

**Comment by mrjarbenne** [comment]
Snippet is a good way to address it. I'm not seeing the notifications though. I've added you as an admin on https://announcementstemplate.commons.hwdsb.on.ca and sent a pending slide through.

**Comment by r-a-y** [comment]
I forgot to mention that only users without the publishing capability
(those with the contributor role) will be able to trigger the email
notification.

I copied this logic from this plugin, but I can remove this check if we
want to.

**Comment by mrjarbenne** [comment]
Yes. I saw that. The pending slide was created by the vbennett username, who is set to contributor.

**Comment by r-a-y** [comment]
Did you check the admin email address listed under "Settings > General"?

It's not your email address, but under the "page" user's email address.

**Comment by mrjarbenne** [comment]
I did. I think I initially thought it would hit anyone with an Administrator role, but it didn't show up in that admin email listed under Settings/General either.
